---
title: "Exploratory analysis"
author: "Shumei Liu"
date: "2024-10-08"
output: github_document
---

```{r, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
weather_df = read_csv("data/weather_df.csv") |>
  mutate(month = lubridate::floor_date(date, unit = "month"))

weather_df
```

## Initial numeric explorations

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp >= 1000)
```

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```

## `group_by`

```{r}
weather_df |>
  group_by(name, month) |>
  ungroup()
```

## counting things

count month observations

```{r}
weather_df |>
  group_by(month) |>
  summarize(n_obs = n()) # n of each month
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(n_obs = n())
```

we can use `count()`

```{r}
weather_df |>
  count(month, name = "n_obs")
```

**NEVER** use base R's `table`

```{r, eval=FALSE}
weather_df |>
  pull(month) |> 
  table() #do NOT use this function
```

other helpful counters

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date)) #每月不同的每一天
```

## A digression on 2x2 tables

```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ "" #if missing anything
  )) |> 
  filter(name != "Molokai_HI") |> 
  group_by(name, cold) |> 
  summarize(count = n())
```


```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ ""
  )) |> 
  filter(name != "Molokai_HI") |> 
  janitor::tabyl(name, cold) #2x2 table
```






